######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 9 14:54:01 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += circle.cpp
